name: Check both branches cron

on:
  schedule:
    - cron: '0 * * * *'

concurrency: cron_update

jobs:
# Disable Early Access until it is updated to U5
#   earlyAccess:
#     uses: mircearoata/satisfactory-modding-actions/.github/workflows/update.yml@master
#     with:
#       branch: EarlyAccess
#     secrets:
#       WWISE_URL: ${{ secrets.WWISE_URL }}
#       ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  experimental:
    uses: mircearoata/satisfactory-modding-actions/.github/workflows/update.yml@master
    with:
      branch: Experimental
    secrets:
      WWISE_URL: ${{ secrets.WWISE_URL }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  experimentalSuccessCheck:
    runs-on: self-hosted
    needs: experimental
    if: always() && needs.experimental.result == 'failure'
    steps:
      - uses: octokit/request-action@v2.x
        name: Disable cron workflow
        with:
          route: PUT /repos/{repo}/actions/workflows/{workflow_id}/disable
          repo: ${{ github.repository }}
          workflow_id: checkCron.yml # The workflow filename
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
