name: Check experimental

on:
  workflow_dispatch:
  repository_dispatch:
    types: [satisfactory-experimental-update]
  

concurrency: update

jobs:
  # TODO check for EXP->EA merges and git merge headers as well
  headers:
    uses: mircearoata/satisfactory-modding-actions/.github/workflows/updateHeaders.yml@master
    with:
      branch: Experimental
    secrets: inherit
  SML:
    uses: mircearoata/satisfactory-modding-actions/.github/workflows/updateSML.yml@master
    needs: [headers]
    if: always() && (needs.headers.result == 'success' || needs.headers.result == 'skipped')
    with:
      branch: Experimental
    secrets: inherit
    
