name: Check experimental

on:
  workflow_dispatch:
  repository_dispatch:
    types: [satisfactory-experimental-update]
  

concurrency: update

jobs:
  # TODO 1.0
  headers:
    uses: ./.github/workflows/updateHeaders.yml
    with:
      branch: Experimental
    secrets: inherit
  SML:
    uses: ./.github/workflows/updateSML.yml
    needs: [headers]
    if: always() && (needs.headers.result == 'success' || needs.headers.result == 'skipped')
    with:
      branch: Experimental
    secrets: inherit
    
