name: Check and update satisfactorymodding/SatisfactoryModLoader

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The game branch (EarlyAccess/Experimental)'
        required: true
        type: string
  workflow_call:
    inputs:
      branch:
        description: 'The game branch (EarlyAccess/Experimental)'
        required: true
        type: string
    secrets:
      WWISE_URL:
        required: false
      ACCESS_TOKEN:
        required: false

jobs:
  check:
    runs-on: self-hosted
    outputs:
     shouldRun: ${{ steps.setShouldRun.outputs.shouldRun }}
     gameVersion: ${{ steps.setGameVersion.outputs.gameVersion }}
    steps:
      - name: Validate branch name
        if: inputs.branch != 'EarlyAccess' && inputs.branch != 'Experimental'
        run: |
          echo "Invalid branch ${{ inputs.branch }}"
          exit 1
      
      - name: Cleanup
        run: Remove-Item * -Recurse -Force -Confirm:$false -ErrorAction Ignore
      
      - name: Download legendary
        run: gh release download --repo derrod/legendary -p "legendary.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Download Satisfactory EarlyAccess version file
        if: inputs.branch == 'EarlyAccess'
        run: .\legendary.exe download CrabEA --no-https --base-path "$Env:GITHUB_WORKSPACE" --prefix="Engine/Binaries/Win64/FactoryGame-Win64-Shipping.version" --game-folder="Satisfactory" -y
      
      - name: Download Satisfactory Experimental version file
        if: inputs.branch == 'Experimental'
        run: .\legendary.exe download CrabTest --no-https --base-path "$Env:GITHUB_WORKSPACE" --prefix="Engine/Binaries/Win64/FactoryGame-Win64-Shipping.version" --game-folder="Satisfactory" -y

      - name: Read Satisfactory version
        id: gameVersion
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'Satisfactory/Engine/Binaries/Win64/FactoryGame-Win64-Shipping.version'
            prop_path: 'Changelist'

      - uses: actions/checkout@v3
        with:
          ref: 'refs/heads/${{ inputs.branch }}'
          path: 'satisfactory-modding'
          repository: 'mircearoata/satisfactory-modding'
      
      - name: Checkout SML
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/auto-header-update'
          path: 'SML'
          repository: 'satisfactorymodding/SatisfactoryModLoader'

      - name: Read current headers version
        id: currentHeadersVersion
        uses: juliangruber/read-file-action@v1
        with:
          path: 'satisfactory-modding/Headers/currentVersion.txt'

      - name: Read current headers version
        id: currentSMLHeadersVersion
        uses: juliangruber/read-file-action@v1
        with:
          path: 'SML/Source/FactoryGame/currentVersion.txt'
          trim: true
      
      - name: Set gameVersion
        id: setGameVersion
        run: echo "gameVersion=${{ steps.gameVersion.outputs.prop }}" >> $Env:GITHUB_OUTPUT
      
      - name: Set shouldRun
        id: setShouldRun
        run: echo "shouldRun=${{ steps.gameVersion.outputs.prop > steps.currentSMLHeadersVersion.outputs.content && steps.gameVersion.outputs.prop == steps.currentHeadersVersion.outputs.content }}" >> $Env:GITHUB_OUTPUT
      
      - name: Cleanup
        run: Remove-Item * -Recurse -Force -Confirm:$false -ErrorAction Ignore
  
  updateSML:
    runs-on: self-hosted
    needs: check
    if: needs.check.outputs.shouldRun == 'true'
    steps:
      - name: Validate branch name
        if: inputs.branch != 'EarlyAccess' && inputs.branch != 'Experimental'
        run: |
          echo "Invalid branch ${{ inputs.branch }}"
          exit 1
      
      - name: Download legendary
        run: gh release download --repo derrod/legendary -p "legendary.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            
      - name: Download jq
        run: gh release download --repo stedolan/jq -p "jq-win64.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Download Satisfactory EarlyAccess
        if: inputs.branch == 'EarlyAccess'
        run: .\legendary.exe download CrabEA --no-https --base-path "$Env:GITHUB_WORKSPACE" --game-folder="Satisfactory" -y
      
      - name: Download Satisfactory Experimental
        if: inputs.branch == 'Experimental'
        run: .\legendary.exe download CrabTest --no-https --base-path "$Env:GITHUB_WORKSPACE" --game-folder="Satisfactory" -y

      - name: Checkout SML
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/auto-header-update'
          path: 'SML'
          repository: 'satisfactorymodding/SatisfactoryModLoader'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Checkout satisfactory-modding
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/${{ inputs.branch }}'
          path: 'satisfactory-modding'
          repository: 'mircearoata/satisfactory-modding'
      
      - name: Checkout satisfactory-modding-actions
        uses: actions/checkout@v3
        with:
          path: 'satisfactory-modding-actions'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Create Unreal Engine directory
        run: mkdir ue
        
      - name: Setup Unreal Engine
        working-directory: ue
        run: |
          gh release download --repo satisfactorymodding/UnrealEngine -p "UnrealEngine-CSS-Editor-Win64.7z.*"
          7z x UnrealEngine-CSS-Editor-Win64.7z.001
          rm UnrealEngine-CSS-Editor-Win64.7z*
          mv lb\\win\\Engine Engine
          reg save "HKCU\Software\Epic Games\Unreal Engine\Builds" UEBuilds.hiv
          .\\SetupScripts\\Register.bat
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Copy latest game source
        run: |
          Remove-Item SML\Source\FactoryGame -Recurse -Force -Confirm:$false -ErrorAction Ignore
          Remove-Item SML\Source\DummyHeaders -Recurse -Force -Confirm:$false -ErrorAction Ignore
          cp satisfactory-modding\FactoryGame\Source\FactoryGame SML\Source -Recurse
          cp satisfactory-modding\FactoryGame\Source\DummyHeaders SML\Source -Recurse
          echo ${{ needs.check.outputs.gameVersion }} | Out-File SML\Source\FactoryGame\currentVersion.txt -Encoding utf8
          
      - name: Add Wwise
        working-directory: SML/Plugins
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "${{ secrets.WWISE_URL }}" -OutFile "Wwise.7z"
          7z x Wwise.7z
          rm Wwise.7z
          
      - name: Checkout UEAssetToolkit
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/dev'
          path: 'UEAssetToolkit'
          repository: 'mircearoata/UEAssetToolkit'
          
      - name: Copy UEAssetToolkit to project
        run: |
          cp UEAssetToolkit\\AssetDumper SML\\Mods -Recurse
          cp UEAssetToolkit\\AssetGenerator SML\\Mods -Recurse
          
      - name: Replace SML with hooks-only version
        run: |
          mkdir SML_TEMP
          mv SML\Mods\SML SML_TEMP\
          mv SML\Mods\SMLEditor SML_TEMP\
          cp satisfactory-modding-actions\SML_HooksOnly\SML SML\Mods -Recurse
          cp satisfactory-modding-actions\SML_HooksOnly\SMLEditor SML\Mods -Recurse
      
      - name: Compile project
        run: |
          .\\ue\\Engine\\Build\\BatchFiles\\Build.bat  -projectfiles -project="$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" -game -rocket -progres
          MSBuild.exe .\\SML\\FactoryGame.sln /p:Configuration="Shipping" /p:Platform="Win64" /t:"Games\FactoryGame"
          MSBuild.exe .\\SML\\FactoryGame.sln /p:Configuration="Development Editor" /p:Platform="Win64" /t:"Games\FactoryGame"
          
      - name: Set SML BuildId
        run: |
          .\jq-win64.exe -r '.BuildId = ""SML""' SML\\Mods\\SML\\Binaries\\Win64\\FactoryGame-Win64-Shipping.modules > FactoryGame-Win64-Shipping.modules
          rm SML\\Mods\\SML\\Binaries\\Win64\\FactoryGame-Win64-Shipping.modules
          mv FactoryGame-Win64-Shipping.modules SML\\Mods\\SML\\Binaries\\Win64
      
      - name: Set AssetDumper BuildId
        run: |
          .\jq-win64.exe -r '.BuildId = ""SML""' SML\\Mods\\AssetDumper\\Binaries\\Win64\\FactoryGame-Win64-Shipping.modules > FactoryGame-Win64-Shipping.modules
          rm SML\\Mods\\AssetDumper\\Binaries\\Win64\\FactoryGame-Win64-Shipping.modules
          mv FactoryGame-Win64-Shipping.modules SML\\Mods\\AssetDumper\\Binaries\\Win64
          
      - name: Copy SML to game
        run: cp SML\\Mods\\SML Satisfactory\\FactoryGame\\Mods\\SML -Recurse
          
      - name: Copy AssetDumper to game
        run: cp SML\\Mods\\AssetDumper Satisfactory\\FactoryGame\\Mods\\AssetDumper -Recurse
          
      - name: Run game and dump assets
        run: Start-Process .\\Satisfactory\\Engine\\Binaries\\Win64\\FactoryGame-Win64-Shipping.exe -ArgumentList "-EpicPortal -DumpAllGameAssets -RootAssetPath=/Game -ExcludePackagePaths=/Game/WwiseAudio -ExcludePackageNames=/Game/Geometry/Meshes/1M_Cube_Chamfer -PackagesPerTick=32 -ExitOnFinish" -NoNewWindow -Wait
      
      - name: Dump configs from pak file
        run: .\\ue\Engine\\Binaries\\Win64\\UnrealPak.exe -Extract "$Env:GITHUB_WORKSPACE\\Satisfactory\\FactoryGame\\Content\\Paks\\FactoryGame-Windows.pak" "$Env:GITHUB_WORKSPACE\\SatisfactoryPak" -Filter="FactoryGame/Config/*.ini"
      
      - name: Read DefaultEngine.ini
        id: defaultEngineIni
        uses: juliangruber/read-file-action@v1
        with:
          path: 'SatisfactoryPak/FactoryGame/Config/DefaultEngine.ini'
      
      - name: Read CollisionProfiles
        id: collisionProfiles
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.defaultEngineIni.outputs.content }}
          regex: '^\[\/Script\/Engine\.CollisionProfile\].+?$(?=\r?\n\[)'
          flags: 'gms'
      
      - name: Update CollisionProfiles
        uses: mingjun97/file-regex-replace@v1
        with:
          include: 'SML\\Config\\DefaultEngine.ini'
          regex: '^\[\/Script\/Engine\.CollisionProfile\].+?$(?=\r?\n\[)'
          flags: 'gms'
          replacement: ${{ steps.collisionProfiles.outputs.match }}
      
      - name: Run asset generator
        run: |
          .\\ue\\Engine\\Binaries\\Win64\\UnrealEditor-Cmd.exe "$Env:GITHUB_WORKSPACE\\SML\\FactoryGame.uproject" -run=AssetGenerator -DumpDirectory="$Env:GITHUB_WORKSPACE\\Satisfactory\\FactoryGame\\AssetDump" -ForceGeneratePackageNames="$Env:GITHUB_WORKSPACE\\satisfactory-modding-actions\\ForceGeneratePackages.txt" -SkipSavePackages="$Env:GITHUB_WORKSPACE\\satisfactory-modding-actions\\SkipSavePackages.txt" -PublicProject -stdout -unattended -NoLogTimes
      
      - name: Remove outdated assets
        run: |
          .\\ue\Engine\\Binaries\\Win64\\UnrealPak.exe -List -csv="$Env:GITHUB_WORKSPACE\\pakContents.csv" -LogCmds="LogPakFile Warning" $Env:GITHUB_WORKSPACE\\Satisfactory\\FactoryGame\\Content\\Paks\\FactoryGame-Windows.pak
          $pakData = Import-Csv .\pakContents.csv
          $pakFiles = $pakData | ForEach-Object { $_.Filename }
          $files = @()
          $prefix = "FactoryGame/Content/"
          foreach ($file in $pakFiles) {
              $filename = $file
              if ($filename.StartsWith($prefix)) {
                  $filename = $filename.Substring($prefix.length)
                  $files += ($Env:GITHUB_WORKSPACE + "\SML\Content\" + $filename).replace('/', '\')
              }
          }
          dir -rec SML\Content\*.* | Where-Object { $files -notcontains $_.Fullname } | Remove-Item
            
      - name: Revert handmade assets
        run: |
          $beaverAssets = Get-Content .\\satisfactory-modding-actions\\BeaverAssets.txt 
          cd SML
          $beaverAssets | Foreach-Object { git reset --hard Content/$_ }
        
      - name: Undo "Replace SML with hooks-only version"
        run: |
          rm -r SML\Mods\SML
          rm -r SML\Mods\SMLEditor
          cp SML_TEMP\SML SML\Mods -Recurse
          cp SML_TEMP\SMLEditor SML\Mods -Recurse
      
      - name: Commit and push
        working-directory: SML
        run: |
          git rm -r --cached Source Content
          git add Source Content
          git add Config/DefaultEngine.ini
          git add Mods/SML/Source/SML/Private/SatisfactoryModLoader.cpp
          git commit -m "Automated update to CL${{ needs.check.outputs.gameVersion }}"
          git push
          
      - name: Restore registry
        if: always()
        working-directory: ue
        run: reg restore "HKCU\Software\Epic Games\Unreal Engine\Builds" UEBuilds.hiv
          
      - name: Archive asset dump
        if: always()
        run: 7z a AssetDump.7z Satisfactory\FactoryGame\AssetDump
          
      - name: Store asset dump
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: AssetDump
          path: |
            AssetDump.7z
          retention-days: 7
      
      - name: Cleanup
        run: Remove-Item * -Recurse -Force -Confirm:$false -ErrorAction Ignore
