name: Check for update Experimental

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The game branch (EarlyAccess/Experimental)'
        required: true
        type: string


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Validate branch name
        if: github.event.inputs.branch != 'EarlyAccess' && github.event.inputs.branch != 'Experimental'
        run: |
          echo "Invalid branch ${{ github.event.inputs.branch }}"
          exit 1
      
      - name: Cleanup
        run: Remove-Item * -Recurse -Force -Confirm:$false -ErrorAction Ignore
      
      - name: Download legendary
        run: gh release download --repo derrod/legendary -p "legendary.exe"
      
      - name: Download Satisfactory EarlyAccess version file
        if: github.event.inputs.branch == 'EarlyAccess'
        run: .\legendary.exe download CrabEA --base-path . --prefix="Engine/Binaries/Win64/FactoryGame-Win64-Shipping.version" --game-folder="Satisfactory" -y
      
      - name: Download Satisfactory Experimental version file
        if: github.event.inputs.branch == 'Experimental'
        run: .\legendary.exe download CrabTest --base-path . --prefix="Engine/Binaries/Win64/FactoryGame-Win64-Shipping.version" --game-folder="Satisfactory" -y

      - name: Read Satisfactory version
        id: gameVersion
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'Satisfactory/Engine/Binaries/Win64/FactoryGame-Win64-Shipping.version'
            prop_path: 'Changelist'

      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/${{ github.event.inputs.branch }}'
          path: 'satisfactory-modding'
          repository: 'mircearoata/satisfactory-modding'

      - name: Read current repo version
        id: currentVersion
        uses: juliangruber/read-file-action@v1
        with:
          path: 'satisfactory-modding/Headers/currentVersion.txt'
      
      - name: Invoke workflow without inputs
        if: steps.gameVersion.outputs.prop > steps.currentVersion.outputs.content
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: updateHeaders
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "branch": "${{ github.event.inputs.branch }}" }'
